### PR TITLE
Bumps EH java client and adds useful config settings for eventhub input plugin

### PR DESCRIPTION
**Pull request by zogwarg**
- com.microsoft.azure:azure-eventhubs '1.0.1'
- partition_list
- decorate_events

### CODE REVIEW

**Comment by brahmnes** [comment]
Hi @zogwarg ,

Thank you for submitting the PR and your interest in contributing to the azureeventhub plugin. However, we are currently working on transitioning this plugin to the logstash repo, where going forward Elastic will own the azure eventhub plugin. As part of the transition, the plugin will also be rewritten to use the Java EventProcessorHost which solves the partition management problem more comprehensively.

An announcement should be posted soon in the readme in this repo. Please visit https://github.com/logstash-plugins/logstash-input-azure_event_hubs to see the current state of that plugin and contribute there.

**Comment by zogwarg** [comment]
Hi @brahmnes, Thanks this is good news. 

I must admit i had done a minimal version bump first. 

Is the plan to move other plugins from this repository to the logstash-plugins one ? I'm thinking specifically of the azure blob one, which would benefit also from a number of improvements.

**Comment by zogwarg** [comment]
@brahmnes Is there a specific timeline for the update of the plugin ? I'd be glad to help if need be. I think including the eventhub metadata is actually even more important than the handling of the partitions. This merge request was really a way of starting that conversation

**Comment by brahmnes** [comment]
Regarding other plugins, @acchen97 may be the best person to comment.
For adding eventhub metadata, @jakelandis can probably answer that question. I would suggest that you add a feature suggestion in the logstash repo so it can be tracked.

**Comment by jakelandis** [comment]
@zogwarg 

I am in the process of re-implementing this with the event processor host API, which allows to persist offsets in the Azure blob store as well allows for multiple logstash instances to work on the same data concurrently. 

I have a work-in-progress PR here: https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/3 (please note, the code isn't ready for review yet, but should show the direction I am taking)

* version is bumped to [latest](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/3/files#diff-c197962302397baf3a4cc36463dce5eaR19)
* metadata will be [optionally included](  https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/3/files#diff-60f81a82f527485b2f113c2329e7462aR43)
* ...and if i understand correctly, the event processor host API obviates the need to declare specific partitions per Logstash instance. 

> Is there a specific timeline for the update of the plugin ?

My goal is early April. 

I have an open discussion at https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues/2 for any feedback on the new direction.

**Comment by brahmnes** [comment]
The plugin at https://github.com/logstash-plugins/logstash-input-azure_event_hubs is now available.
If the feature you need is still not there, please contribute to that repo

**Pull request closed without merging**
